{ ... }: {
  imports = [
    /etc/nixos/hardware-configuration.nix
    ./fingerprint.nix
    ./kernel.nix
    ./ppd.nix
    ./flatpak.nix
    ./allow_unfree.nix
    ./boot_loader.nix
    ./desktop_environment.nix
    ./display_manager.nix
    ./keymap.nix
    ./enable_flakes.nix
    ./state_version.nix
    ./locale.nix
    ./networking.nix
    ./printing.nix
    ./sound.nix
    ./time.nix
    ./git.nix
    ./graphic.nix
    ./podman.nix
    ./libvirtd.nix
    ./garbage_collection.nix
    ./store.nix
    ./qt.nix
    ./cpu.nix
    ./terminal.nix
    ./editor.nix
    ./nh.nix
  ];
}
