{ ... }: {
  imports = [
    ./gsnap.nix
    ./file.nix
    ./twingate.nix
    ./orca_slicer.nix
    ./fira_code_nerdfont.nix
    ./ripgrep.nix
    ./nmap.nix
    ./cutter.nix
    ./ghidra.nix
    ./bruno.nix
    ./caido.nix
    ./icedtea_web.nix
    ./flipper.nix
    ./gdu.nix
    ./l2tp.nix
    ./lazygit.nix
    ./rustup.nix
    ./unzip.nix
    ./openssl.nix
    ./noto.nix
    ./jq.nix
    ./playerctl.nix
    ./nerdfonts.nix
    ./discordo.nix
    ./fira_code.nix
    ./browsers
  ];
}
